[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-data"
version = "0.1.0"
workspace = "../"

[dependencies]
ammonia = "1.0.1"
chrono = "0.4.0"
derive_builder = "0.5.1"
dotenv = "0.10.1"
error-chain = "0.11.0"
itertools = "0.7.6"
lazy_static = "1.0.0"
log = "0.3.8"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
rayon = "0.9.0"
reqwest = "0.8.2"
rfc822_sanitizer = "0.3.3"
rss = "1.2.1"
url = "1.6.0"
xdg = "2.1.0"
futures = "0.1.17"
hyper = "0.11.12"
tokio-core = "0.1.12"
hyper-tls = "0.1.2"
native-tls = "0.1.4"

[dependencies.diesel]
features = ["sqlite"]
version = "1.0.0"

[dependencies.diesel_migrations]
features = ["sqlite"]
version = "1.0.0"

[dev-dependencies]
rand = "0.4.1"
tempdir = "0.3.5"
criterion = "0.1.2"

[[bench]]
name = "bench"
harness = false
