[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-data"
version = "0.1.0"
workspace = "../"

[dependencies]
chrono = "0.4"
dotenv = "0.10.1"
error-chain = "0.11"
lazy_static = "0.2"
log = "0.3"
rayon = "0.9"
reqwest = "0.8"
rfc822_sanitizer = "0.3"
rss = "1.1"
xdg = "2.1"

[dependencies.diesel]
features = ["sqlite"]
version = "0.16"

[dependencies.diesel_codegen]
features = ["sqlite"]
version = "0.16"

[dev-dependencies]
rand = "0.3"
tempdir = "0.3"
