[package]
name = "hammond-data"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
workspace = "../"

[dependencies]
rfc822_sanitizer = "0.3"
rayon = "0.8"
reqwest = "0.8"
error-chain = "0.11"
log = "0.3"
diesel = { version = "0.16", features = ["sqlite"] }
diesel_codegen = { version = "0.16", features = ["sqlite"] }
xdg = "2.1"
lazy_static = "0.2"
rss = "1.1"
chrono = "0.4"
# overwrite diesel dependancy that disables a feature rss depends upon
dotenv = "*"

[dev-dependencies]
tempdir = "0.3"
rand = "0.3"
