[package]
name = "hammond-data"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]

[dependencies]
rayon = "0.8.2"
error-chain = "0.11.0"
log = "0.3.8"
loggerv = "0.3.0"
reqwest = "0.7.3"
diesel = { version = "0.16.0", features = ["sqlite", "deprecated-time", "chrono"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
xdg = "2.1.0"
lazy_static = "0.2.8"

