[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-data"
version = "0.1.0"
workspace = "../"

[dependencies]
chrono = "0.4.0"
dotenv = "0.10.1"
error-chain = "0.11.0"
lazy_static = "0.2.10"
log = "0.3.8"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
rayon = "0.9.0"
reqwest = "0.8.1"
rfc822_sanitizer = "0.3.3"
rss = "1.1.0"
xdg = "2.1.0"

[dependencies.diesel]
features = ["sqlite"]
# version = "0.16.0"
git = "https://github.com/diesel-rs/diesel.git"

[dependencies.diesel_codegen]
features = ["sqlite"]
git = "https://github.com/diesel-rs/diesel.git"

[dev-dependencies]
rand = "0.3.18"
tempdir = "0.3.5"
