[package]
name = "hammond-data"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]

[dependencies]
rfc822_sanitizer = "0.3.0"
rayon = "0.8.2"
hyper = "0.11.2"
reqwest = "0.7.3"
error-chain = "0.11.0"
log = "0.3.8"
loggerv = "0.3.0"
diesel = { version = "0.16.0", features = ["sqlite", "deprecated-time", "chrono"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
xdg = "2.1.0"
lazy_static = "0.2.8"
rss = { version = "1.1.0", features = ["from_url"]}
dotenv = "*"

[dev-dependencies]
tempdir = "0.3.5"