unstable_features = true
max_width = 100
comment_width = 100
wrap_comments = true
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
condense_wildcard_suffixes = false
format_strings = true
normalize_comments = true
reorder_imports = true
