[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-downloader"
version = "0.1.0"
workspace = "../"

[dependencies]
error-chain = "0.11.0"
hyper = "0.11.6"
log = "0.3.8"
mime_guess = "1.8.2"
rand = "0.3.18"
reqwest = "0.8.1"
tempdir = "0.3.5"

[dependencies.diesel]
features = ["sqlite"]
git = "https://github.com/diesel-rs/diesel.git"

[dependencies.hammond-data]
path = "../hammond-data"
