[package]
name = "hammond-downloader"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
workspace = "../"

[dependencies]
hammond-data = {path = "../hammond-data"}
error-chain = "0.11"
log = "0.3"
reqwest = "0.7"
hyper = "0.11"
diesel = { version = "0.16", features = ["sqlite"] }
rss = { version = "1.1", features = ["from_url"]}
dotenv = "*"
