[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-downloader"
version = "0.1.0"
workspace = "../"

[dependencies]
error-chain = "0.11"
hyper = "0.11"
log = "0.3"
mime_guess = "1.8"
rand = "0.3"
reqwest = "0.8"
tempdir = "0.3"

[dependencies.diesel]
features = ["sqlite"]
version = "0.16"

[dependencies.hammond-data]
path = "../hammond-data"
