[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-downloader"
version = "0.1.0"
workspace = "../"

[dependencies]
error-chain = "0.11.0"
hyper = "0.11.15"
log = "0.4.1"
mime_guess = "1.8.3"
reqwest = "0.8.4"
tempdir = "0.3.5"
glob = "0.2.11"

[dependencies.hammond-data]
path = "../hammond-data"

