[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
name = "hammond-downloader"
version = "0.1.0"
workspace = "../"

[dependencies]
error-chain = "0.11.0"
hyper = "0.11.9"
log = "0.3.8"
mime_guess = "1.8.3"
reqwest = "0.8.1"
tempdir = "0.3.5"

[dependencies.diesel]
features = ["sqlite"]
version = "0.99.0"

[dependencies.hammond-data]
path = "../hammond-data"
