[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
build = "build.rs"
name = "podcasts-gtk"
version = "0.1.0"
workspace = "../"

[dependencies]
chrono = "0.4.4"
crossbeam-channel = "0.2.3"
gdk = "0.8.0"
gdk-pixbuf = "0.4.0"
glib = "0.5.0"
gstreamer = "0.11.4"
gstreamer-player = "0.11.3"
humansize = "1.1.0"
lazy_static = "1.0.2"
log = "0.4.3"
loggerv = "0.7.1"
open = "1.2.1"
rayon = "1.0.2"
send-cell = "0.1.3"
url = "1.7.1"
failure = "0.1.1"
failure_derive = "0.1.1"
regex = "1.0.2"
reqwest = "0.8.6"
serde_json = "1.0.24"
# html2text = "0.1.8"
html2text = { git = "https://github.com/alatiera/rust-html2text" }

[dependencies.gtk]
features = ["v3_22"]
version = "0.4.1"

[dependencies.gio]
features = ["v2_50"]
version = "0.4.1"

[dependencies.podcasts-data]
path = "../podcasts-data"

[dependencies.podcasts-downloader]
path = "../podcasts-downloader"

[dev-dependencies]
pretty_assertions = "0.5.1"
