[package]
name = "hammond-gtk"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
workspace = "../"

[dependencies]
gtk = { version = "0.2", features = ["v3_22"]}
glib = "0.3"
gdk-pixbuf = "0.2"
hammond-data = {path = "../hammond-data"}
diesel = { version = "0.16", features = ["sqlite"] }