[package]
name = "hammond-gtk"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
workspace = "../"

[dependencies]
gtk = { version = "0.2", features = ["v3_22"]}
gdk = "0.6"
glib = "0.3"
gio = "0.2"
gdk-pixbuf = "0.2"
libc = "0.2"

gio-sys = "0.4"
glib-sys = "^0.4"

loggerv = "0.4"
log = "0.3"
open = "1.2"
dissolve = "0.2"
rayon = "0.8"

hammond-data = {path = "../hammond-data"}
hammond-downloader = {path = "../hammond-downloader"}
