[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
build = "build.rs"
name = "hammond-gtk"
version = "0.1.0"
workspace = "../"

[dependencies]
chrono = "0.4.0"
dissolve = "0.2.2"
gdk = "0.7.0"
gdk-pixbuf = "0.3.0"
gio = "0.3.0"
glib = "0.4.0"
humansize = "1.0.2"
lazy_static = "1.0.0"
log = "0.3.8"
loggerv = "0.6.0"
open = "1.2.1"
rayon = "0.9.0"
regex = "0.2.3"
send-cell = "0.1.2"

[dependencies.diesel]
features = ["sqlite"]
version = "0.99.0"

[dependencies.gtk]
features = ["v3_22"]
version = "0.3.0"

[dependencies.hammond-data]
path = "../hammond-data"

[dependencies.hammond-downloader]
path = "../hammond-downloader"
