[package]
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
build = "build.rs"
name = "hammond-gtk"
version = "0.1.0"
workspace = "../"

[dependencies]
dissolve = "0.2.2"
gdk = "0.7.0"
gdk-pixbuf = "0.3.0"
gio = "0.3.0"
glib = "0.4.0"
log = "0.3.8"
loggerv = "0.5.1"
open = "1.2.1"
rayon = "0.9.0"

[dependencies.diesel]
features = ["sqlite"]
git = "https://github.com/diesel-rs/diesel.git"

[dependencies.diesel_codegen]
features = ["sqlite"]
git = "https://github.com/diesel-rs/diesel.git"

[dependencies.gtk]
features = ["v3_22"]
version = "0.3.0"

[dependencies.hammond-data]
path = "../hammond-data"

[dependencies.hammond-downloader]
path = "../hammond-downloader"
